Brainstorming
onelocom/knowledge-base pull request #2
Opened 2020-11-13 16:36 UTC by israelfenor

@arnau look the content updated. I think now fits better with the ideas we've talked last week.

2020-11-16 07:47 UTC, arnau commented on README.md
> +This repository keeps the source for Onelo's knowledge base. It serves as a playground for ideas to make Onelo more useful.
Is there a problem in using 80 character lines? 🤔

2020-11-16 07:50 UTC, arnau commented on content/onelo-api.md
> +- Read a directory recursively (all subdirectories included) and get the filename of all files inside
Other parts of this repo use `*` for lists instead of `-`. Would be best to stick to a single style.

2020-11-16 07:52 UTC, arnau commented on content/whats-onelo.md
> +> Future versions could be able to use remote data sources like Dropbox, Github repositories, etc accessed via API
Shouldn't this blockquote be a paragraph instead?

2020-11-16 07:53 UTC, arnau commented on content/whats-onelo.md
> +> Future versions could be able to use remote data sources like Dropbox, Github repositories, etc accessed via API
The question applies to all blockquotes in the document

2020-11-16 07:54 UTC, arnau commented on content/whats-onelo.md
> +> Should Onelo find all files or only files that it can be able to inspect?
Should be:

> [...] or just files that it is able to inspect?

2020-11-16 07:57 UTC, arnau commented on content/whats-onelo.md
> +    - links between files written along content
> [...] written in the content.

or

> [...] written as part of the content

2020-11-16 07:59 UTC, arnau commented on content/whats-onelo.md
> +Explicit structure is obvious, and it not have much added value, but could be useful in some scenarios.
> [...] and it has no added value

Aside, I don't understand why you claim that "could be useful in some scenarios"? An explicit link is quite fundamental to me.

2020-11-16 08:01 UTC, arnau commented on content/whats-onelo.md
> +At the end those representation should be exported as some set of data that can be consumed or persisted as a file using the best approach, for example, use [mermaid](https://mermaid-js.github.io) or
> **In the end**, this representation [...]

Either use "these representations" or "this representation". I'm not sure which one you intended to write.

2020-11-16 08:04 UTC, arnau commented on content/whats-onelo.md
> +An structure exported (as stream of data or as a file) could be displayed using the more useful representation depending on the nature of the structure (some kind of graph, a classic hierarchy, etc).
> A structure exported (as a stream of data or as a file) could be displayed using different representations depending on the nature of the structure.

2020-11-16 08:04 UTC, arnau commented on content/whats-onelo.md
> +User could swap between the differents structures extracted (if there are more than one).
> A user

or

> The user

2020-11-16 08:05 UTC, arnau commented on content/whats-onelo.md
> +We have saved the tools for last. Tools are the things we need to accomplish the things explained in the previous sections.
Sorry, this explanation doesn't help me understand what do you mean by tools.

2020-11-16 08:06 UTC, arnau requested changes
There are a few things that need fixing and some others where I need clarification.

2020-11-16 17:01 UTC, israelfenor commented on README.md
> +This repository keeps the source for Onelo's knowledge base. It serves as a playground for ideas to make Onelo more useful.
We are in 2020, old man!!! XD

2020-11-16 17:03 UTC, israelfenor commented on content/onelo-api.md
> +- Read a directory recursively (all subdirectories included) and get the filename of all files inside
Ok!

2020-11-16 17:07 UTC, israelfenor commented on content/whats-onelo.md
> +> Future versions could be able to use remote data sources like Dropbox, Github repositories, etc accessed via API
Those sentences will be removed and added as ideas in the Project Management Board. It has been a way to wrote down those questions. I'll delete it

2020-11-16 17:14 UTC, israelfenor commented on content/whats-onelo.md
> +> Should Onelo find all files or only files that it can be able to inspect?
Done

2020-11-16 17:14 UTC, israelfenor commented on content/whats-onelo.md
> +    - links between files written along content
Done

2020-11-16 17:15 UTC, israelfenor commented on content/whats-onelo.md
> +User could swap between the differents structures extracted (if there are more than one).
Done

2020-11-16 17:17 UTC, israelfenor commented on content/whats-onelo.md
> +We have saved the tools for last. Tools are the things we need to accomplish the things explained in the previous sections.
Yes, it's not a good sentence, It put there as a placeholder. I'll write some documentation about parts of Onelo and this section will be more clear.

2020-11-16 17:18 UTC, israelfenor commented on content/whats-onelo.md
> +An structure exported (as stream of data or as a file) could be displayed using the more useful representation depending on the nature of the structure (some kind of graph, a classic hierarchy, etc).
Done

2020-11-16 17:19 UTC, israelfenor commented on content/whats-onelo.md
> +At the end those representation should be exported as some set of data that can be consumed or persisted as a file using the best approach, for example, use [mermaid](https://mermaid-js.github.io) or
Done

2020-11-18 16:53 UTC, israelfenor commented on content/whats-onelo.md
> +Explicit structure is obvious, and it not have much added value, but could be useful in some scenarios.
Done

2020-11-19 06:52 UTC, arnau approved these changes

2020-11-19 18:26 UTC, merged